"""empty message

Revision ID: 3f27dcbe5657
Revises: 2890fb158f8f
Create Date: 2023-01-09 20:25:52.337868

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f27dcbe5657"
down_revision = "2890fb158f8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_model", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user_model", sa.Column("last_login", sa.DateTime(), nullable=True))
    op.add_column("user_model", sa.Column("coins", sa.BigInteger(), nullable=False))
    op.add_column(
        "user_model",
        sa.Column("last_daily_reward", sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_model", "last_daily_reward")
    op.drop_column("user_model", "coins")
    op.drop_column("user_model", "last_login")
    op.drop_column("user_model", "created_at")
    # ### end Alembic commands ###
